name: Infrastructure as Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate
        with:
          GCLOUD_JSON: ${{ secrets.GCLOUD_JSON }}

      # - name: Terraform plan
      #   id: plan
      #   run: terraform plan
      #   continue-on-error: false

      # - name: Save plan path to GITHUB_OUTPUT
      #   run: echo "PLAN_PATH=tfplan" >> $GITHUB_OUTPUT

      # - name: Terraform apply
      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      #   run: terraform apply -auto-approve $PLAN_PATH
